### ISSUE TITLE
How should the middleware priority be set?

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#1]
900 is probably good, but I noticed all the priorities in one project I'm working on are >1000.  Should this come before middleware that postprocesses?  What other sort of middleware is there, and should it come before or after those?

Anyways, this might be something good to expand on in the readme.

**Comment by fcanobrash** [comment]
Thinking about it, the best place right now is at the end of the list of spider middlewares, being the last middleware by numeric order - the first `process_spider_output` to be invoked -
We'll add a new feature in short to include middlewares in tests.
Added this information to the README (https://github.com/fcanobrash/scrapy-autounit/commit/182c36e6a9c462d7d7a6a68b8e44f6d211abe1d0) so I'll close the issue.
