### ISSUE TITLE
Assumes utf-8 responses

### ISSUE THREAD

**Issue by wRAR** [scrapinghub/scrapy-autounit#11]
Looks like response bodies are saved with `response.body.decode('utf-8', 'replace')`, this breaks tests for pages that are not in UTF-8. Shouldn't it just use `response.text` or, if needed, use various encoding-related Response attributes?

**Comment by fcanobrash** [comment]
Agree, we're going to fix this, thanks.

**Comment by fcanobrash** [comment]
Solved in https://github.com/scrapinghub/scrapy-autounit/commit/c40664b81d4e59e699521d2a518c8240ca0ea58b.
Thanks for pointing it out, closing the issue.
