### ISSUE TITLE
Undocumented serialization requirements

### ISSUE THREAD

**Issue by wRAR** [scrapinghub/scrapy-autounit#12]
It looks like Spider objects must be serializable (with pickle in the current version), this should be documented and I wonder if there are ways to overcome this. For example, I'm currently getting `Can't pickle local object 'LxmlLinkExtractor.__init__.<locals>.<lambda>'` for a CrawlSpider.

**Comment by MariusMez** [comment]
Same error for my first test : `AttributeError: Can't pickle local object 'Crawler.__init__.<locals>.<lambda>'`

Maybe something like dill https://github.com/uqfoundation/dill can help ?

**Comment by rooterkyberian** [comment]
I have hit the same issue with `SitemapSpider`

**Comment by andrewbaxter** [comment]
Hey @fcanobrash mind if I take this?
