### ISSUE TITLE
Test grouping

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#13]
I have a spider that runs differently depending on a parameter and currently all the tests are mixed together.  Would it be possible to separate tests into different folders by spider arguments (`-a`) as well as spider/callback?

Maybe something like what the feed export plugin does where you can use any attribute?

**Comment by fcanobrash** [comment]
Solved in PR https://github.com/scrapinghub/scrapy-autounit/pull/20
