### ISSUE TITLE
Unclear when to have AUTOUNT_ENABLED on

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#15]
The documentation says
> Then make sure you enable Scrapy Autounit:...

I think it's likely to confuse people who will read that and add AUTOUNIT_ENABLED to their settings.py.  Some people may get distracted and stop reading there, or when they read the Note: the contradiction (`make sure you enable Scrapy Autounit` and `Make sure you turn AUTOUNIT_ENABLED on only when ...`) not understand what they're supposed to do and misuse it.

**Comment by fcanobrash** [comment]
Totally agree, would adding this caveat make things clearer?
> Keep in mind that as long as AUTOUNIT_ENABLED is on, each time you run a spider tests/fixtures are going to be generated for its callbacks.
This means that if you have your tests/fixtures ready to go, this setting should be off to prevent undesired overwrites.
Each time you want to regenerate your tests (e.g.: due to changes in your spiders), you can turn this on again and run your spiders as usual.

**Comment by andrewbaxter** [comment]
Oh yeah, that looks good.  I think the main thing that was confusing here is that the docs currently have the line `make sure you enable Scrapy Autounit` along with the SETTING and it's not obvious that this is only when recording tests.

If you have a PR I might be able to give you better feedback.

**Comment by fcanobrash** [comment]
No PR so far but this is the commit in case you want to review it, thanks - 
https://github.com/scrapinghub/scrapy-autounit/commit/f4156680ce163bb756bfecbf6114b70e7c2f015e

**Comment by andrewbaxter** [comment]
Ah, that looks really clear to me!

**Comment by fcanobrash** [comment]
Great, solved in https://github.com/scrapinghub/scrapy-autounit/commit/f4156680ce163bb756bfecbf6114b70e7c2f015e
