### ISSUE TITLE
`meta` modification

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#18]
Had an issue with `_autounit` appearing in the fixtures' metadata.  What happened is that in the previous callback the spider did:
1. meta = response.meta
2. meta['x'] = y
3. yield Request(..., meta=meta)

Somehow this made it written to the fixture.

Is there any way this could be worked around or raise an alert or something (ideally worked around)?

**Comment by andrewbaxter** [comment]
Actually, this might be a simpler issue - just that `_autounit` is added to the `Request` metadata accidentally.  IMO spiders shouldn't be carelessly transferring `meta` parameters so a warning/error might be better here (? - if there are legacy spiders doing it though a workaround would be better).

**Comment by fcanobrash** [comment]
Solved in https://github.com/scrapinghub/scrapy-autounit/commit/227c32cef801a5cd9d3917ebc896f5199d8e34d9.
