### ISSUE TITLE
Delete tests before rerecording?

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#24]
Pretty easy to detect, but if you don't delete the old tests before re-recording and a callback name changes or something I think it's possible that old tests will be left around (and break).

Maybe a note about this in the docs as a best practice would be helpful.

**Comment by fcanobrash** [comment]
Solved in https://github.com/scrapinghub/scrapy-autounit/commit/88b413febe76c2275110aadd8c00d7bb02da07ef
