### ISSUE TITLE
Allow "." in spider names

### ISSUE THREAD

**Issue by ejulio** [scrapinghub/scrapy-autounit#26]
I created a dummy spider for `quotes.toscrape.com` and set `name = 'quotes.toscrape.com'`.
After running `scrapy crawl quotes.toscrape.com` it generated the tests as expected.
However, when I ran `python -m unittest` I got
```
E
======================================================================
ERROR: autounit.tests.quotes.toscrape (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: autounit.tests.quotes.toscrape
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
ModuleNotFoundError: No module named 'autounit.tests.quotes'
```

Also `ls autounit/tests/` returned `__init__.py  __pycache__  quotes.toscrape.com`.

My fix idea is to replace `.` with `_` as done when we run `scrapy genspider quotes.toscrape.com quotes.toscrape.com`

**Comment by andrewbaxter** [comment]
I'm on this :D

**Comment by andrewbaxter** [comment]
I'm copying how genspider does it, thanks for the suggestion @ejulio
