### ISSUE TITLE
Support pytest

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#28]
The issue we saw is pytest is confusing arguments in a test helper method as fixtures and bombing out.

**Comment by andrewbaxter** [comment]
https://pytest.org/en/latest/unittest.html#unittest says they should be compatible, but I haven't read it completely.

**Comment by andrewbaxter** [comment]
I wonder if pytest is accidentally identifying autounit internal methods as test methods (due to naming?) -- maybe this is a non issue.

**Comment by fcanobrash** [comment]
It was a naming issue indeed. Solved in #45, thanks!
