### ISSUE TITLE
Support request instances in meta attributes

### ISSUE THREAD

**Issue by VMRuiz** [scrapinghub/scrapy-autounit#48]
We have a common pattern where we store a list of `request` object in the meta attribute:

```
meta = {
  'callstack': [ request_profile, request_related, request_facebook],
  'item': item
}
```

This help us to build the workflow for each item individualy while keeping each parse method independent from others.

Currently, unit test fails because it tries to pickle the entire meta attribute which request that references the spider and hence the crawler thorough their callback methods.

As suggestions, meta could also be inspect in a recursive way to detect Request and transform then to dict as required.

**Comment by VMRuiz** [comment]
Additionaly, I did some test around this:

`AUTOUNIT_REQUEST_SKIPPED_FIELDS` - Can't be used to skip the meta field because right now it's only applied when reconstructing data in already created test. So, we can't skipped the meta attribute during test creation to avoid the error.

In order to have a more grained control, I added `AUTOUNIT_META_SKIPPED_FIELDS` to ignore only the desired fields on the meta attribute. 

I did some test by getting rid of the fields in `AUTOUNIT_REQUEST_SKIPPED_FIELDS` / `AUTOUNIT_META_SKIPPED_FIELDS` before pickled the output into tests and it got rid of the error during test creation, but when I tried to execute the test it fail because the missing meta attributes were required in order to execute some parts of the tests.

**Comment by andrewbaxter** [comment]
So basically the skipping meta fields isn't a solution in this case?

**Comment by VMRuiz** [comment]
@andrewbaxter ,

No is not, because when the spider access the `callstack` key as part of the parse method execution it will fail because such key was deleted/skipped when the test was created in order to avoid the error.

Maybe we could have some kind of mock instead of deleting it / doing a nested processing of the meta attribute, but I'm not sure how that could be implemented in a way that would solved it.

**Comment by andrewbaxter** [comment]
Autounit already does other nested processing, so I think that's probably a reasonable solution.  @fcanobrash mind if I take this?  Any comments on the implementation before I start?
