### ISSUE TITLE
Pathlib dep missing new features

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#64]
For projects relying on Python 3.5+'s `pathlib` some functions aren't implemented in the `pathlib` backport required here.  In Python 3.6 when Autounit gets installed the backport is also installed and importing pathlib results in objects that are missing newly introduced methods.

I think this affects projects with spidermon installed, which may use some newer pathlib methods.

Just some quick research into solutions:

- `pathlib2` seems to be a more recently updated pathlib replacement (but I'm not sure how long it will continue to be updated)
- Maybe the dependency can be conditional on python version?  I'm not sure how poetry/pipenv would handle this though.
- Using pyproject.toml instead of setup.py?  Pyproject.toml has a syntax for specifying conditional dependencies I think.
- A hack to have autounit itself install pathlib if it fails to import?  And then remove it entirely from dependencies.

**Comment by fcanobrash** [comment]
@andrewbaxter, maybe just using `os.path` instead of `pathlib` is an option? What do you think?

**Comment by andrewbaxter** [comment]
Yeah, that might be best here.
