### ISSUE TITLE
Spider name mangling not used in inspect

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#70]
Sorry for the emptyish issue.  Basically if you have a spider named `abc.xyz` autounit will record tests to the `abc_xyz` directory, but if you try to inspect `abc.xyz` inspect looks for a `abc.xyz` directory and can't find it, raising an error.

Manually mangling the name lets it work, so I don't think this is a significant issue.

**Comment by fcanobrash** [comment]
Solved in https://github.com/scrapinghub/scrapy-autounit/commit/69f09bfcfc42536d365d0a73106ecfcd1ded4817
