### ISSUE TITLE
Tool to update fixtures from test output

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/scrapy-autounit#71]
I think this probably has limited implications, but if you update a spider and the only thing that changes is the items produced it may be nice to be able to automatically update the fixture without rerecording.

For instance, callback x is recorded as producing:
```
[{"value": 4}, {"value: 5}]
```

and then you update the spider and now it produces:
```
[{"value": 4}, {"value": 5}, {"value": 7}]
```

The corresponding autounit test will fail.  In this case I see it and go, "oh yeah that's what it should actually output" and run the tool saying "update fixture x for spider y callback z".

**Comment by fcanobrash** [comment]
Solved in https://github.com/scrapinghub/scrapy-autounit/commit/1719f7455b3c5e018bc77c2d06221404ac1ac3d1
