### ISSUE TITLE
Readme default for AUTOUNIT_EXCLUDED_HEADERS

### ISSUE THREAD

**Issue by rendaw** [scrapinghub/scrapy-autounit#8]
Is the default `[]` or does it include `Authorization` + co?  I was wondering if it's possible to include `Authorization` in your tests if you override `AUTOUNIT_EXCLUDED_HEADERS` as empty.

**Comment by fcanobrash** [comment]
No, you can't include `Authorization` headers in fixtures so far.
Authorization headers are excluded always regardless of `AUTOUNIT_EXCLUDED_HEADERS` setting. If you set this setting to `[]`, Authorization headers will still be excluded.

I guess we could set the default setting to `[...auth headers...]` and if the developer wants to include them just sets the setting as `[]`.

Anyway, should we allow the user include `Authorization` headers as an option?

**Comment by fcanobrash** [comment]
No, you can't include `Authorization` headers in fixtures so far.
Authorization headers are excluded always regardless of `AUTOUNIT_EXCLUDED_HEADERS` setting. If you set this setting to `[]`, Authorization headers will still be excluded.

I guess we could set the default setting to `[...auth headers...]` and if the developer wants to include them just sets the setting as `[]`.

Anyway, should we allow the user include `Authorization` headers as an option?

**Comment by rendaw** [comment]
I would IMO, just in case someone does want to test it.

**Comment by fcanobrash** [comment]
Okay, I'll change this 👍

**Comment by fcanobrash** [comment]
Solved in https://github.com/fcanobrash/scrapy-autounit/commit/13053f9f6fe0adf85a514b71905d07c7d216f92f - Closing the issue.
